### ISSUE TITLE
please help me，I don't know how to run the train.py

### ISSUE THREAD

**Issue by chenchch94** [kuangliu/pytorch-retinanet#43]
can you tell me ?

Traceback (most recent call last):
  File "train.py", line 15, in <module>
    from loss import FocalLoss
  File "H:\datasets\tianchi_lvcai\tianchi_lvcai_fusai\pytorch-retinanet-master\loss.py", line 7, in <module>
    from utils import one_hot_embedding
  File "H:\datasets\tianchi_lvcai\tianchi_lvcai_fusai\pytorch-retinanet-master\utils.py", line 242, in <module>
    _, term_width = os.popen('stty size', 'r').read().split()
ValueError: not enough values to unpack (expected 2, got 0)

**Comment by Brozhao** [comment]
run on the terminal

**Comment by doublemanyu** [comment]
Because there is no command named "stty size" in Windows, so you should run in Linux, or you set a number for term_width in utils.py
