### ISSUE TITLE
how to run train.py???

### ISSUE THREAD

**Issue by 237014845** [kuangliu/pytorch-retinanet#51]
python train.py 
==> Preparing data..

Epoch: 0
Traceback (most recent call last):
  File "train.py", line 114, in <module>
    train(epoch)
  File "train.py", line 75, in train
    loss = criterion(loc_preds, loc_targets, cls_preds, cls_targets)
  File "/home/hs/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hs/hs/pytorch/pytorch-retinanet-580/loss.py", line 99, in forward
    print('loc_loss: %.3f | cls_loss: %.3f' % (loc_loss.item()/num_pos, cls_loss.item()/num_pos), end=' | ')
  File "/home/hs/anaconda3/lib/python3.6/site-packages/torch/tensor.py", line 320, in __rdiv__
    return self.reciprocal() * other
RuntimeError: reciprocal is not implemented for type torch.cuda.LongTensor

**Comment by 237014845** [comment]
anyone can help me？？

**Comment by Imagery007** [comment]
1.Run script get_state_dict.py first to get a base model.
2.Put the generated model in model/net.pth.
3.Then start the training with python train.py --lr=1e-3.

**Comment by Imagery007** [comment]
1.Run script get_state_dict.py first to get a base model.
2.Put the generated model in model/net.pth.
3.Then start the training with python train.py --lr 0.001.

**Comment by klauscf** [comment]
> model/net.pth

where can i get the net.pth file
